---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: azure-disk
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: westus
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "sqldb-pv"
  annotations:
    volume.beta.kubernetes.io/storage-class: "azure-disk"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guestbook-db
spec:
  template:
    metadata:
      labels:
        app: guestbook-db
        component: guestbook-db
    spec:
      containers:
      - name: guestbook-db
        image: microsoft/mssql-server-linux
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: Pass@word1
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: sqldb-home
      volumes:
      - name: sqldb-home
        persistentVolumeClaim:
          claimName: sqldb-pv
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: guestbook-db
    component: guestbook-db
  name: guestbook-db
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 10433
      targetPort: 1433
      name: guestbook-db-port
  selector:
    app: guestbook-db
    component: guestbook-db