apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guestbook-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: guestbook-web
        app: guestbook-web
    spec:
      containers:
      - name: guestbook-web
        image: khacr.azurecr.io/guestbook-web:aspnetcore-296
        env:
        - name: SQLSERVER
          value: "40.85.157.254,10433"
        - name: SQL_ID
          value: "sa"
        - name: SQL_PWD
          value: "Pass@word1"
        - name: SQL_DB
          value: "guestbookdb"
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-web
  labels:
    app: guestbook-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    name: guestbook-web-port
  selector:
    run: guestbook-web