apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guestbook-go-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: guestbook-go-web
        app: guestbook-go-web
    spec:
      containers:
      - name: guestbook-go-web
        image: kevingbb/guestbook-web:go
        env:
        - name: SQLSERVER
          value: "<PUBLIC_IP_ADDRESS_GOES_HERE>"
        - name: SQLPORT
          value: "10433"
        - name: SQLID
          value: "sa"
        - name: SQLPWD
          value: "<PASSWORD_GOES_HERE"
        - name: SQLDB
          value: "guestbookdb"
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-go-web
  labels:
    app: guestbook-go-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    run: guestbook-go-web